### ISSUE TITLE
Space between images before hovering 

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/fancy-hover-boxes#1]
Hi @jessjodoin,

I started working on this assignment a week or two ago and I ran into some issues when I was running it through Markbot. As I went through the lesson, it never mentioned defining the image width/height, and I had a huge screenshot difference with Markbot so in my CSS I defined both and that helped with some of my screenshot problems. 

The final issue I'm encountering is when I run it through Markbot it's showing a small white space between the images on the 320px screen size. I've tried inspecting my webpage and there's no padding or margin that I can see to remove so I'm not sure what I should be targeting to remove the additional space. It odd too because the white space it there when I initially load the screen and once I hover my mouse over the image and then move it off, that white space disappears. Attached is a screenshot from Markbot to hopefully help explain the issue I'm having

<img width="317" alt="Screen Shot 2020-11-13 at 11 48 44 AM" src="https://user-images.githubusercontent.com/55094049/99098911-b0beea00-25a7-11eb-89dc-2dbaf0b21b39.png">

**Comment by JessJodoin** [comment]
You shouldn't have to specify the height. The issue with the images is probably the default display setting.
By default images are set to `display: inline-block;` and for whatever reason inline-block adds spacing so if you set the images to `display: block;` it'll remove those added spacing.

Let me know if that helps! 😄

**Comment by riannazandbelt** [comment]
Changing it to display: block worked perfectly and fixed it! Thanks 😊
